### ISSUE TITLE
token-metadata-test-client location

### ISSUE THREAD

**Issue by gunagu** [theskeletoncrew/air-support#2]
Hi,
Thank you for making an amazing tools. I have problem with the location of 
token-metadata-test-client.
When I do "make generate". I got this error.
./2_generate_prints/mint.sh: line 35: ../../metaplex/rust/target/debug/metaplex-token-metadata-test-client: No such file or directory

May be you can give me some information what I need to change. I find the folder, and I can't found it in rust folder.

Thank you

**Comment by cosimo-rip** [comment]
Hi - have you run the “cargo build” step from the README on the latest version of metaplex?

**Comment by gundulawn** [comment]
> Hi - have you run the “cargo build” step from the README on the latest version of metaplex?

Yes, I did

**Comment by gundulawn** [comment]
Nvm, I wrong write the Metaplex Path.

But, have a new error 

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', token-metadata\test\src\main.rs:256:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thank you so much

**Comment by skeletoncrewrip** [comment]
The important part in the error log here is:
Program log: Maximum editions printed already

You’ve hit the limit that you configured for number of prints allowed from your master.
