### ISSUE TITLE
error with distribute.sh

### ISSUE THREAD

**Issue by Tishj** [theskeletoncrew/air-support#3]
If the recipients list is smaller than the minted addresses, it looks like the action has failed.
(Ideally you don't want the recipients list to be smaller than the list of minted tokens, but still it makes sense to make the error more obvious than a loop of errors)

Proposed solution:
Loop over the recipients list length instead of the token list length

Or - check if the recipient list is the same length as the minted token list and stop the script if they're not equal?

**Comment by skeletoncrewrip** [comment]
Thanks for these suggestions. Checking that they are equal is probably the way to go. Maybe a warning, asking for confirmation to proceed if the lengths don’t match.

And, we could exit the loop early if we hit the end of either list.

**Comment by migui3230** [comment]
@skeletoncrewrip ill try this issue!

**Comment by cosimo-rip** [comment]
thanks @migui3230!

**Comment by migui3230** [comment]
@cosimo-rip #8

**Comment by cosimo-rip** [comment]
Closed by #8
